# If installed via a package manager, these paths may be:
# /usr/share/gtkgreet-builder/examples/minimal/...
[ui]
style = /usr/local/share/gtkgreet-builder/examples/minimal/style.css
layout = /usr/local/share/gtkgreet-builder/examples/minimal/layout.ui

[core]
root = main_root
initial_answer = Answer
read_command = Command
pam_prompt_answer = Answer
