# If installed via a package manager, these paths may be:
# /usr/share/gtkgreet-builder/examples/showcase/...
[ui]
style = /usr/local/share/gtkgreet-builder/examples/showcase/style.css
layout = /usr/local/share/gtkgreet-builder/examples/showcase/layout.ui

[core]
initial_answer = InitialAnswer
read_command = Command
pam_prompt_answer = PromptAnswer

[optional]
question_prompt = Prompt
error_prompt = Prompt
info_prompt = Prompt
command_list = Command
cancel = Cancel
submit = Submit
poweroff = PowerOff
suspend = Suspend
reboot = Reboot
hibernate = 

[state.initial]
visible = Prompt;Submit

[state.pam]
visible = Prompt;Cancel;Submit

[session]
environments = sway;start-hyprland;gnome-session
