# gtkgreet-builder configuration template
# Copy this file to /etc/greetd and modify the values as needed

[ui]
# Paths to the UI layout and optional CSS stylesheet
# Currently only absolute file paths are supported
style = /absolute/path/to/style.css
layout = /absolute/path/to/layout.ui

[core]
# Mandatory roles that must be provided valid widget IDs defined in your .ui file
root = 
initial_answer = 
read_command = 
pam_prompt_answer = 

[optional]
# Optional widget bindings. Leave empty if unused
question_prompt = 
error_prompt = 
info_prompt = 
command_list = 
cancel = 
submit =
poweroff = 
suspend = 
reboot = 
hibernate = 

[state.initial]
# Widgets to be shown during initial state
# (semicolon-separated list)
visible = 

[state.pam]
# Widgets to be shown during PAM prompts
# (semicolon-separated list)
visible = 

[session]
# Additional session launch commands can be provided here
# (semicolon-separated list)
environments = 
